
[colors.primary]
background = "#2b2820"
foreground = "#dddddd"

[cursor.style]
blinking = "Off"
shape = "Block"

[font]
size = 13.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "BoldItalic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "MediumItalic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 0.9

[window.padding]
x = 5
y = 5
